#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

# Mis llamados
exec-once = waybar
exec-once = btm
exec-once = systemctl --user start hyprpolkitagent
exec-once = swaync
exec-once = hyprpaper
exec-once = hyprlock
exec-once = hypridle
