$font =			 JetBrainsMono Nerd Font
$COLOR_INPUT = 		 rgba(255, 87, 87, 0.5)
$COLOR_CHECK =	 	 rgba(140, 40, 40, 0.7)
$COLOR_TEXT =	 	 rgb(217, 217, 217)
$COLOR_FAIL = 		 rgb(144, 64, 58)


general {
	hide_cursor = false
}

animations {
	enabled = true
	bezier = linear, 1, 1, 0, 0
	animation = fadeIn, 1, 5, linear
	animation = fadeOut, 1, 5, linear
	animation = inputFieldDots, 1, 2, linear
}

background {
	monitor =
	path = ~/.config/hypr/wp/hyprlock.jpg
	blur_passes = 0
	blur_size = 0
}

# Shape of the username
shape {
	monitor = 
	size = 20%, 5%
	color = $COLOR_INPUT
	rounding = -1

	position = -623, 0
	halign = center
	valign = center
}

# Username
label {
	monitor =
	text = $USER
	font_size = 21
	font_family = $font
	color = $COLOR_TEXT

	position = -623, 0
	halign = center
	valign = center
}

# Textfield for the password
input-field {
	monitor = 
	size = 20%, 5%
	outline_thickness = 0
	inner_color = $COLOR_INPUT

	check_color = $COLOR_CHECK
	fail_color = $COLOR_FAIL

	font_color = $COLOR_TEXT
	fade_on_empty = false

	font_family = &font
	font_size = 21
	placeholder_text = 🔒
	fail_text = $PAMFAIL

	dots_size = 0.3
	dots_spacing = 0.3

	position = 145, -80
	halign = left
	valign = center

	dots_center = true
}

# BIENVENIDO 
label {
	monitor =
	text = Bienvenido!
	font_size = 55
	font_family = $font
	color = $COLOR_TEXT

	position = 94, -203
	halign = left
	valign = top
}

# TIME 
label {
	monitor = 
	# text = cmd[update:1000] date +"%H:%M"
	# text = $TIME
	text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
	font_size = 40
	font_family = $font
	color = $COLOR_TEXT

	position = 257, -291
	halign = left
	valign = top
}

#DATE 
label {
	monitor = 
	text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
	font_size = 20
	font_family = $font
	color = $COLOR_TEXT

	position = 170, -368
	halign = left
	valign = top
}
