format = """
[](#79a4c2)\
$username\
[](bg:#4e7a96 fg:#79a4c2)\ 
$directory\
[](fg:#4e7a96 bg:#396581)\ 
$git_branch\
$git_status\
[](fg:#396581 bg:#648fac)\ 
$nodejs\
$rust\
$golang\
$php\
[](fg:#648fac bg:#053f58)\
$time\
[ ](fg:#053f58)\
\n$character"""

[username]
show_always = true
style_user = "fg:#ffffff bg:#79a4c2"
style_root = "fg:#ffffff bg:#79a4c2"
format = "[ $user ]($style)"

[directory]
style = "fg:#ffffff bg:#4e7a96"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documentos" = "󰈙 "
"Descargas" = " "
"Music" = " "
"Imágenes" = " "
"~" = "󰓎 "
"home" = " "

[git_branch]
symbol = " "
style = "bg:#396581"
format = '[[ $symbol $branch ](fg:#ffffff bg:#396581)]($style)'

[git_status]
style = "bg:#396581"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#396581)]($style)'

[nodejs]
symbol = ""
style = "bg:#648fac"
format = '[[ $symbol ($version) ](fg:#648fac bg:#648fac)]($style)'

[rust]
symbol = ""
style = "bg:#648fac"
format = '[[ $symbol ($version) ](fg:#648fac bg:#648fac)]($style)'

[golang]
symbol = ""
style = "bg:#648fac"
format = '[[ $symbol ($version) ](fg:#648fac bg:#648fac)]($style)'

[php]
symbol = ""
style = "bg:#648fac"
format = '[[ $symbol ($version) ](fg:#648fac bg:#648fac)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#053f58"
format = '[[  $time ](fg:#ffffff bg:#053f58)]($style)'
