format = """
[](#6d5033)\
$username\
[](bg:#593d22 fg:#6d5033)\ 
$directory\
[](fg:#593d22 bg:#4f3419)\ 
$git_branch\
$git_status\
[](fg:#4f3419 bg:#63462b)\ 
$nodejs\
$rust\
$golang\
$php\
[](fg:#63462b bg:#3b2306)\
$time\
[ ](fg:#3b2306)\
\n$character"""

[username]
show_always = true
style_user = "fg:#ffffff bg:#6d5033"
style_root = "fg:#ffffff bg:#6d5033"
format = "[ $user ]($style)"

[directory]
style = "fg:#ffffff bg:#593d22"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documentos" = "󰈙 "
"Descargas" = " "
"Music" = " "
"Imágenes" = " "
"~" = "󰓎 "
"home" = " "

[git_branch]
symbol = " "
style = "bg:#4f3419"
format = '[[ $symbol $branch ](fg:#ffffff bg:#4f3419)]($style)'

[git_status]
style = "bg:#4f3419"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#4f3419)]($style)'

[nodejs]
symbol = ""
style = "bg:#63462b"
format = '[[ $symbol ($version) ](fg:#63462b bg:#63462b)]($style)'

[rust]
symbol = ""
style = "bg:#63462b"
format = '[[ $symbol ($version) ](fg:#63462b bg:#63462b)]($style)'

[golang]
symbol = ""
style = "bg:#63462b"
format = '[[ $symbol ($version) ](fg:#63462b bg:#63462b)]($style)'

[php]
symbol = ""
style = "bg:#63462b"
format = '[[ $symbol ($version) ](fg:#63462b bg:#63462b)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#3b2306"
format = '[[  $time ](fg:#ffffff bg:#3b2306)]($style)'
